### ISSUE TITLE
ERROR: Can't find the 'iwgetid' command

### ISSUE THREAD

**Issue by theniwo** [sdushantha/wifi-password#4]
```
~ locate iwgetid
/sbin/iwgetid

~ wifi-password
ERROR: Can't find the 'iwgetid' command
```

This was run on Ubuntu 18.04.5 LTS

**Comment by Adrianordp** [comment]
I'm pulling the fix

**Comment by Adrianordp** [comment]
The pull request #5 fixes it.

**Comment by sdushantha** [comment]
Closing this issue since it has been fixed in #5

**Comment by littlediobolic** [comment]
Just tested the newest version and this error seems to persist. 

> $ sudo wifi-password
> ERROR: Can't find the 'iwgetid' command

**Comment by theniwo** [comment]
I get:
`ERROR: You need to run '/home/niwo/.local/bin/wifi-password' as root`
and when run with sudo
`sudo: wifi-password: command not found`
:D

**Comment by sdushantha** [comment]
I don't have a Linux machine at the moment. Would you guys be willing to try and figure out why this error is arising?

**Comment by littlediobolic** [comment]
Sure thing, after looking my box does not have the iwgetid binary. I am trying to locate and install it and see if that fixes the problem.

**Comment by theniwo** [comment]
Isn't it possible for you to run a virtual machine?

**Comment by sdushantha** [comment]
@littlediobolic The only computer I have is my school MacBook. We unfortunately have restrictions when it comes to installing apps on our computers.

**Comment by littlediobolic** [comment]
That's the problem, which I guess was obvious. I resolved by installing the wireless-tools package on my machine to get the iwgetid command. 

For Arch/Manjaro: sudo pacman -S wireless-tools
For Ubuntu: sudo apt-get install wireless-tools

I'm not super programming savvy so I probably couldnt write something to install those packages on install, but I could make a PR with comments to isntall wireless-tools if you'd like?

**Comment by theniwo** [comment]
>  install those packages on install
Not a good idea. Better print an error message that the package is missing. Also, if it is required it should to be mentioned in the readme

**Comment by Adrianordp** [comment]
> `ERROR: You need to run '/home/niwo/.local/bin/wifi-password' as root`
> and when run with sudo
> `sudo: wifi-password: command not found`

@theniwo Uninstall with sudo and without sudo:
`pip3 uninstall wifi-password ; sudo pip3 uninstall wifi-password`

Then reinstall via:
`sudo pip3 install wifi-password`.

Tell us if it works now.

**Comment by theniwo** [comment]
`ERROR: Cound not find password`

(Wasn't that typo also fixed in the pr by ImranVirani)

**Comment by janhsteiner** [comment]
> That's the problem, which I guess was obvious. I resolved by installing the wireless-tools package on my machine to get the iwgetid command.
> 
> For Arch/Manjaro: sudo pacman -S wireless-tools
> For Ubuntu: sudo apt-get install wireless-tools
> 
> I'm not super programming savvy so I probably couldnt write something to install those packages on install, but I could make a PR with comments to install wireless-tools if you'd like?

The package for Arch/Manjaro is actually called `wireless_tools` so the command is `sudo pacman -S wireless_tools`

**Comment by littlediobolic** [comment]
> The package for Arch/Manjaro is actually called `wireless_tools` so the command is `sudo pacman -S wireless_tools`

Yup just noticed and edited my comment. Im working on a PR to add this to the README and to the error message

**Comment by sdushantha** [comment]
I am closing this PR as this issue seems to be fixed

**Comment by engineer22** [comment]
> I am closing this PR as this issue seems to be fixed

I'm in Debian 10, the problem persist after installing wireless-tools via APT.

**Comment by littlediobolic** [comment]
@engineer22 
Is iwgetid present on your system?

`which iwgetid`

**Comment by Adrianordp** [comment]
@engineer22 Your output for
`/etc/NetworkManager/system-connections/`
has your connection configuration files for each SSID you've connected. On Ubuntu, these files has the extension nmconnection. How does Debian's connection files look like?

**Comment by engineer22** [comment]
@Adrianordp @littlediobolic 

there are the results with the SSID's manipulated:

> sudo which iwgetid
/usr/sbin/iwgetid

> cd /etc/NetworkManager/system-connections/
ls
name1.nmconnection name2.nmconnection

**Comment by Adrianordp** [comment]
Your SSID appears when you input
`iwgetid -r`
on terminal?

**Comment by engineer22** [comment]
Yes it does.

> sudo iwgetid -r
name2

**Comment by engineer22** [comment]
Yes it does.

> sudo iwgetid -r
name2

**Comment by littlediobolic** [comment]
Does `cat /etc/NetworkManager/system-connections/{ssid}.nmconnection | grep psk=` return anything? Replacing {ssid} for name2 of course

**Comment by engineer22** [comment]
I found the problem.

I have 2 SSIDs, one named name1 and one named name2. Both have space between them:

> name 1 & name 2

after reading again the results of **/etc/NetworkManager/system-connections/** they're displayed  as 'name 1' & 'name 2'.
If I create a new AP and name it as name3 (no space), the script prints successfully.

The program needs to take into consideration that some SSIDs may have space between their names.
